# Author: Claire Gregg

version: '3.7'
services:
  ingress:
    build:
      dockerfile:
        ingress/Dockerfile
    container_name: ingress
    network_mode: "host"

  client:
    build:
      dockerfile:
        client/Dockerfile
    network_mode: "host"
    volumes:
      - ./output:/output
    depends_on:
      - ingress
      - worker

    deploy:
      mode: replicated
      replicas: 10

  worker:
    build:
      dockerfile:
        worker/Dockerfile
    network_mode: "host"
    depends_on:
      - ingress

    deploy:
      mode: replicated
      replicas: 10
  
  interactive_client:
    build:
      dockerfile: 
        interactive_client/Dockerfile
    network_mode: "host"
    volumes:
      - ./interactive_output:/interactive_output
    depends_on:
      - ingress
      - worker
    stdin_open: true
    tty: true

  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump
