version: '3.7'
services:
  ingress:
    build: ./ingress/
    container_name: ingress
    network_mode: "host"

  client1:
    build: ./client/
    container_name: client1
    network_mode: "host"
    depends_on:
      - ingress
      - worker1

  worker1:
    build: ./worker/
    container_name: worker1
    network_mode: "host"
    depends_on:
      - ingress
