version: '3.7'
services:
  ingress:
    build: ./ingress/
    container_name: ingress
    network_mode: "host"

  client:
    build: ./client/
    network_mode: "host"
    volumes:
      - ./output:/output
    depends_on:
      - ingress
      - worker

    deploy:
      mode: replicated
      replicas: 2

  worker:
    build: ./worker/
    network_mode: "host"
    depends_on:
      - ingress

    deploy:
      mode: replicated
      replicas: 2

  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump
