version: '3.7'
services:
  ingress:
    build:
      dockerfile:
        ingress/Dockerfile
    container_name: ingress
    network_mode: "host"

  client:
    build:
      dockerfile:
        client/Dockerfile
    network_mode: "host"
    volumes:
      - ./output:/output
    depends_on:
      - ingress
      - worker

    deploy:
      mode: replicated
      replicas: 3

  worker:
    build:
      dockerfile:
        worker/Dockerfile
    network_mode: "host"
    depends_on:
      - ingress

    deploy:
      mode: replicated
      replicas: 3

  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump
